# Default values for api-gateway.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

ingress:
  name: apigateway
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: "letsencrypt-prod"
  hosts:
    - host: nginxapp.example.com
      paths:
        - path: /
          pathType: Prefix
          service:
            name: nginx-web
            port:
              number: 80
  tls:
  - hosts:
    - nginxapp.example.com
    secretName: nginxapp-example-tls
