pipeline {
    agent any

    tools {
        nodejs "NodeJs"
    }

    stages {
        stage('Clone') {
            steps {
                git 'https://github.com/NguyenPhuocMinh/story-bootstrap.git'
            }
        }
        stage('Install') {
            steps {
                sh 'npm install'
                sh 'npm run lerna:bootstrap'
            }
        }
        stage('Publish') {
            steps {
                sh 'npm run lerna:publish'
            }
        }
    }
}
