pipeline {
    agent {
        docker {
            image 'node:16.14.0-alpine:3.14'
        }
    }
    stages {
        stage('Clone') {
            steps {
                git 'https://github.com/NguyenPhuocMinh/story-bootstrap.git'
            }
        }
        stage('Install') {
            steps {
                sh 'npm install'
                sh 'npm run lerna:bootstrap'
            }
        }
        stage('ESLint') {
            steps {
                sh 'npm run lint:check'
            }
        }
        stage('Test') {
            steps {
                sh 'npm run test'
            }
            post {
                always {
                    junit 'junit.xml'
                }
            }
        }
        stage('Build') {
            steps {
                sh 'npm run lerna:build'
            }
        }

    }
}
