pipeline {
    agent any

    tools {
        nodejs "NodeJs"
    }

    stages {
        stage('Clone') {
            steps {
                git 'https://github.com/NguyenPhuocMinh/story-bootstrap.git'
            }
        }
        stage('Install') {
            steps {
                sh 'npm install'
                sh 'npm run lerna:bootstrap'
            }
        }
        stage('ESLint') {
            steps {
                sh 'npm run lint:check'
            }
        }
        stage('Test') {
            steps {
                sh 'npm run test'
            }
        }
        stage('Build') {
            steps {
                sh 'npm run lerna:build'
            }
        }
        stage('Publish to npm') {
            steps {
                echo "//npm.pkg.github.com/:_authToken=$NPM_TOKEN" > .npmrc
                sh 'npm run lerna:publish from-git --no-git-tag-version --no-push --yes'
            }
        }
    }
}
