export enum AUTH_TYPES {
  AUTH_REGISTER = 'AUTH_REGISTER',
  AUTH_LOGIN = 'AUTH_LOGIN',
  AUTH_LOGOUT = 'AUTH_LOGOUT',
  AUTH_CHECK = 'AUTH_CHECK',
  AUTH_ERROR = 'AUTH_ERROR',
  AUTH_GET_PERMISSIONS = 'AUTH_GET_PERMISSIONS'
}
