export enum USER_TYPES {
  USER_REGISTER = 'USER_REGISTER',
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGIN_LOADING = 'USER_LOGIN_LOADING',
  USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE',
  USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS',
  USER_CHECK = 'USER_CHECK',
  USER_CHECK_SUCCESS = 'USER_CHECK_SUCCESS',
  USER_LOGOUT = 'USER_LOGOUT'
}
